version: '3'

services:
  redis-slave-2:
    image: redis:7.2.5
    container_name: redis-slave-2
    restart: always
    ports:
      - "6381:6379"
    command: sh /usr/local/etc/redis/docker-entrypoint.sh
    volumes:
      - ../config-template/slave/redis.conf.template:/usr/local/etc/redis/redis.conf.template
      - ../config-template/slave/docker-entrypoint-slave.sh:/usr/local/etc/redis/docker-entrypoint.sh
    env_file:
      - ../config-template/.env
    networks:
      redis-network:
        ipv4_address: 172.28.3.31
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "|", "grep", "PONG"]
      interval: 30s
      timeout: 10s
      retries: 5

  sentinel-3:
    image: redis:7.2.5
    container_name: sentinel-3
    restart: always
    ports:
      - "26381:26379"
    command: sh /usr/local/etc/redis/docker-entrypoint.sh
    volumes:
      - ../config-template/sentinel/sentinel.conf.template:/usr/local/etc/redis/sentinel.conf.template
      - ../config-template/sentinel/docker-entrypoint-sentinel.sh:/usr/local/etc/redis/docker-entrypoint.sh
    env_file:
      - ../config-template/.env
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping", "|", "grep", "PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      redis-network:
        ipv4_address: 172.28.3.33

networks:
  redis-network:
    external: true
