version: '3'
services:
  s3:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: s3minio.local
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - server
      - --certs-dir
      - /opt/minio/certs
      - /data
      - --console-address
      - ":9001"
    volumes:
      - ./private.key:/opt/minio/certs/private.key
      - ./public.crt:/opt/minio/certs/public.crt
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge
